/* GENERATED by schema/wire_schema.py -- do not edit by hand.
 *
 * Wire format for forwarding winemetal render commands across a machine
 * boundary. Regenerate with:  python3 schema/wire_schema.py
 */
#ifndef WMT_WIRE_H
#define WMT_WIRE_H
#include <stdint.h>
#include <string.h>

#define WMTW_VERSION 1

#define WMTW_MAX_BATCH_BYTES 1048576u
#define WMTW_MAX_RECORDS 4096u
#define WMTW_MAX_SIDECAR_BYTES 65536u
#define WMTW_MAX_ARRAY_COUNT 256u

/* Static assertions fire at compile time on BOTH sides, so a layout change
 * that only one side picked up cannot reach the wire. Token-pasting the
 * expression into an identifier does not work -- use _Static_assert. */
#if defined(__cplusplus)
#  define WMTW_ASSERT(c, m) static_assert(c, m)
#else
#  define WMTW_ASSERT(c, m) _Static_assert(c, m)
#endif

enum wmtw_op {
    WMTW_OP_Nop                          = 0,
    WMTW_OP_UseResource                  = 1,
    WMTW_OP_SetVertexBuffer              = 2,
    WMTW_OP_SetVertexBufferOffset        = 3,
    WMTW_OP_SetFragmentBufferOffset      = 21,
    WMTW_OP_SetFragmentBuffer            = 4,
    WMTW_OP_SetFragmentTexture           = 10,
    WMTW_OP_SetFragmentBytes             = 11,
    WMTW_OP_SetRasterizerState           = 12,
    WMTW_OP_SetViewports                 = 13,
    WMTW_OP_SetScissorRects              = 14,
    WMTW_OP_SetPSO                       = 15,
    WMTW_OP_SetDSSO                      = 16,
    WMTW_OP_SetBlendFactorAndStencilRef  = 17,
    WMTW_OP_Draw                         = 19,
    WMTW_OP_DrawIndexed                  = 20,
    /* one past the highest opcode -- NOT the number of record types,
       since opcodes are sparse (winemetal's numbering is preserved) */
    WMTW_OP__MAX
};
#define WMTW_OP_COUNT 15   /* record types actually implemented */

/* Every record starts with this. `size` covers the header and body but NOT
 * sidecar data, which lives in a separate region addressed by offset -- so a
 * decoder can walk the stream without understanding any record it does not
 * implement. */
struct wmtw_hdr { uint16_t op; uint16_t version; uint32_t size; };

struct wmtw_viewport { double x, y, width, height, znear, zfar; };
struct wmtw_scissor  { uint64_t x, y, width, height; };

/* Batch prologue. Sidecar data follows the record stream. */
struct wmtw_batch {
    uint32_t magic;          /* 'WMTB' */
    uint16_t version;
    uint16_t encoder_kind;   /* 0 render, 1 compute, 2 blit */
    uint32_t record_bytes;
    uint32_t record_count;
    uint32_t sidecar_bytes;
    uint32_t reserved;
};
#define WMTW_BATCH_MAGIC 0x42544D57u

struct wmtw_nop {
    struct wmtw_hdr h;
};
WMTW_ASSERT(sizeof(struct wmtw_nop) == 8, "wmtw_nop layout changed on one side only");

struct wmtw_useresource {
    struct wmtw_hdr h;
    uint64_t  resource;
    uint64_t  usage;
    uint64_t  stages;
};
WMTW_ASSERT(sizeof(struct wmtw_useresource) == 32, "wmtw_useresource layout changed on one side only");

struct wmtw_setvertexbuffer {
    struct wmtw_hdr h;
    uint64_t  buffer;
    uint64_t  offset;
    uint64_t  index;
};
WMTW_ASSERT(sizeof(struct wmtw_setvertexbuffer) == 32, "wmtw_setvertexbuffer layout changed on one side only");

struct wmtw_setvertexbufferoffset {
    struct wmtw_hdr h;
    uint64_t  offset;
    uint64_t  index;
};
WMTW_ASSERT(sizeof(struct wmtw_setvertexbufferoffset) == 24, "wmtw_setvertexbufferoffset layout changed on one side only");

struct wmtw_setfragmentbufferoffset {
    struct wmtw_hdr h;
    uint64_t  offset;
    uint64_t  index;
};
WMTW_ASSERT(sizeof(struct wmtw_setfragmentbufferoffset) == 24, "wmtw_setfragmentbufferoffset layout changed on one side only");

struct wmtw_setfragmentbuffer {
    struct wmtw_hdr h;
    uint64_t  buffer;
    uint64_t  offset;
    uint64_t  index;
};
WMTW_ASSERT(sizeof(struct wmtw_setfragmentbuffer) == 32, "wmtw_setfragmentbuffer layout changed on one side only");

struct wmtw_setfragmenttexture {
    struct wmtw_hdr h;
    uint64_t  texture;
    uint64_t  index;
};
WMTW_ASSERT(sizeof(struct wmtw_setfragmenttexture) == 24, "wmtw_setfragmenttexture layout changed on one side only");

struct wmtw_setfragmentbytes {
    struct wmtw_hdr h;
    uint64_t  index;
    uint32_t bytes_offset;   /* into the sidecar region */
    uint32_t bytes_count;    /* elements, not bytes */
};
WMTW_ASSERT(sizeof(struct wmtw_setfragmentbytes) == 24, "wmtw_setfragmentbytes layout changed on one side only");

struct wmtw_setrasterizerstate {
    struct wmtw_hdr h;
    uint32_t  front_facing;
    uint32_t  cull_mode;
    uint32_t  fill_mode;
    uint32_t  depth_clip_mode;
    float     depth_bias;
    float     slope_scale;
    float     depth_bias_clamp;
    uint32_t  pad0;
};
WMTW_ASSERT(sizeof(struct wmtw_setrasterizerstate) == 40, "wmtw_setrasterizerstate layout changed on one side only");

struct wmtw_setviewports {
    struct wmtw_hdr h;
    uint32_t viewports_offset;   /* into the sidecar region */
    uint32_t viewports_count;    /* elements, not bytes */
};
WMTW_ASSERT(sizeof(struct wmtw_setviewports) == 16, "wmtw_setviewports layout changed on one side only");

struct wmtw_setscissorrects {
    struct wmtw_hdr h;
    uint32_t scissors_offset;   /* into the sidecar region */
    uint32_t scissors_count;    /* elements, not bytes */
};
WMTW_ASSERT(sizeof(struct wmtw_setscissorrects) == 16, "wmtw_setscissorrects layout changed on one side only");

struct wmtw_setpso {
    struct wmtw_hdr h;
    uint64_t  pso;
};
WMTW_ASSERT(sizeof(struct wmtw_setpso) == 16, "wmtw_setpso layout changed on one side only");

struct wmtw_setdsso {
    struct wmtw_hdr h;
    uint64_t  dsso;
    uint32_t  stencil_ref;
    uint32_t  pad0;
};
WMTW_ASSERT(sizeof(struct wmtw_setdsso) == 24, "wmtw_setdsso layout changed on one side only");

struct wmtw_setblendfactorandstencilref {
    struct wmtw_hdr h;
    float     r;
    float     g;
    float     b;
    float     a;
    uint32_t  stencil_ref;
    uint32_t  pad0;
};
WMTW_ASSERT(sizeof(struct wmtw_setblendfactorandstencilref) == 32, "wmtw_setblendfactorandstencilref layout changed on one side only");

struct wmtw_draw {
    struct wmtw_hdr h;
    uint64_t  primitive;
    uint64_t  start;
    uint64_t  count;
    uint64_t  instances;
    uint64_t  base_instance;
};
WMTW_ASSERT(sizeof(struct wmtw_draw) == 48, "wmtw_draw layout changed on one side only");

struct wmtw_drawindexed {
    struct wmtw_hdr h;
    uint64_t  primitive;
    uint64_t  index_count;
    uint64_t  index_type;
    uint64_t  index_buffer;
    uint64_t  index_offset;
    uint64_t  instances;
    uint64_t  base_vertex;
    uint64_t  base_instance;
};
WMTW_ASSERT(sizeof(struct wmtw_drawindexed) == 72, "wmtw_drawindexed layout changed on one side only");

#endif
